import { Language } from './types';

export const UI_STRINGS: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Factur_totCOS',
    appSubtitle: 'AI-Powered Invoice Intelligence',
    uploadTitle: 'Upload Your Invoices',
    uploadSubtitle: 'Drag & drop files here or click to browse',
    uploadProcessing: 'AI is processing your document...',
    dashboard: 'Dashboard',
    totalInvoices: 'Total Invoices',
    totalAmount: 'Total Amount',
    spendingBySupplier: 'Spending by Supplier',
    invoices: 'Invoices',
    searchPlaceholder: 'Search by supplier, date, or amount...',
    exportCSV: 'Export to CSV',
    tableProvider: 'Provider',
    tableDate: 'Date',
    tableTotal: 'Total',
    tableTax: 'Tax',
    tableActions: 'Actions',
    delete: 'Delete',
    noInvoices: 'No invoices found. Upload one to get started!',
    noInvoicesMatch: 'No invoices match your search.',
    chatWithAI: 'Chat with AI Assistant',
    chatTitle: 'AI Financial Assistant',
    chatPlaceholder: 'Ask about your finances...',
    chatWelcome: 'Hello! How can I help you with your invoices today?',
    admin: 'Admin',
    viewer: 'Viewer',
    language: 'Language',
    role: 'Role',
    errorTitle: 'An Error Occurred',
    errorUpload: 'Failed to upload and process the invoice.',
    errorChat: 'The AI assistant is having trouble responding.',
  },
  es: {
    appName: 'Factur_totCOS',
    appSubtitle: 'Inteligencia de Facturas con IA',
    uploadTitle: 'Sube Tus Facturas',
    uploadSubtitle: 'Arrastra y suelta archivos aquí o haz clic para buscar',
    uploadProcessing: 'La IA está procesando tu documento...',
    dashboard: 'Panel de Análisis',
    totalInvoices: 'Facturas Totales',
    totalAmount: 'Importe Total',
    spendingBySupplier: 'Gasto por Proveedor',
    invoices: 'Facturas',
    searchPlaceholder: 'Buscar por proveedor, fecha o importe...',
    exportCSV: 'Exportar a CSV',
    tableProvider: 'Proveedor',
    tableDate: 'Fecha',
    tableTotal: 'Total',
    tableTax: 'Impuestos',
    tableActions: 'Acciones',
    delete: 'Eliminar',
    noInvoices: 'No se encontraron facturas. ¡Sube una para empezar!',
    noInvoicesMatch: 'Ninguna factura coincide con tu búsqueda.',
    chatWithAI: 'Chatea con el Asistente de IA',
    chatTitle: 'Asistente Financiero de IA',
    chatPlaceholder: 'Pregunta sobre tus finanzas...',
    chatWelcome: '¡Hola! ¿Cómo puedo ayudarte con tus facturas hoy?',
    admin: 'Admin',
    viewer: 'Lector',
    language: 'Idioma',
    role: 'Rol',
    errorTitle: 'Ocurrió un Error',
    errorUpload: 'No se pudo subir y procesar la factura.',
    errorChat: 'El asistente de IA tiene problemas para responder.',
  },
};
